### ISSUE TITLE
SCRIPT ERROR: @el_business/server.lua:19

### ISSUE THREAD

**Issue by Janicki92** [Elipse458/el_business#2] opened 2019-12-19 01:03 UTC
SCRIPT ERROR: @el_business/server.lua:19: attempt to index a nil value (field ‘?’)

    `callback` (@el_business/server.lua:98)
    fn `(@mysql-async/lib/MySQL.lua:197)`

**Comment by Elipse458** [comment] 2019-12-19 15:46
can you send me a dump of your businesses table from the database?

**Comment by dutchplayers** [comment] 2019-12-21 23:39
```
-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 22, 2019 at 12:39 AM
-- Server version: 10.4.10-MariaDB
-- PHP Version: 7.3.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `essentialmode`
--

-- --------------------------------------------------------

--
-- Table structure for table `businesses`
--

CREATE TABLE `businesses` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `address` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `description` varchar(75) COLLATE utf8mb4_bin NOT NULL,
  `blipname` varchar(75) COLLATE utf8mb4_bin DEFAULT NULL,
  `owner` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `price` int(11) NOT NULL,
  `earnings` int(11) NOT NULL,
  `position` text COLLATE utf8mb4_bin NOT NULL,
  `stock` int(11) NOT NULL DEFAULT 0,
  `stock_price` int(11) NOT NULL DEFAULT 100,
  `employees` text COLLATE utf8mb4_bin NOT NULL,
  `taxrate` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Dumping data for table `businesses`
--

INSERT INTO `businesses` (`id`, `name`, `address`, `description`, `blipname`, `owner`, `price`, `earnings`, `position`, `stock`, `stock_price`, `employees`, `taxrate`) VALUES
(1, 'Gucci Store', 'Some random street 1337, Beverly Hills', 'Very fancy store', NULL, NULL, 1000000, 10000, '{\"buy\":{\"x\":2524.11, \"y\":-382.22, \"z\":93},\"actions\":{\"x\":2526.04,\"y\":-379.43,\"z\":92.99}}', 47, 100, '{}', NULL),
(2, 'Gucci Store 2', 'Some random street 1338, Beverly Hills', 'Very fancy store', NULL, NULL, 1333337, 1337, '{\"buy\":{\"x\":0.0,\"y\":0.0,\"z\":0.0},\"actions\":{\"x\":0.0,\"y\":0.0,\"z\":0.0}}', 0, 100, '{}', NULL),
(3, 'Noodle Doodle', 'Blokkenpark 1', 'De lekkerste Noodles uit Nieuwstad', 'Noodle Doodle Winkel', 'steam:11000010db5c7fb', 10000, 30, '{\"buy\":{\"z\":29.310102462769,\"x\":272.48986816406,\"y\":-965.12017822266},\"actions\":{\"z\":29.310102462769,\"x\":272.48986816406,\"y\":-965.12017822266}}', 0, 3, '[]', 0.1),
(4, 'Limey\'s', 'Blokkenpark 3', 'De lekkerste smoothies uit Nieuwstad!', 'Limey\'s winkel', NULL, 10000, 30, '{\"actions\":{\"y\":-1026.9453125,\"x\":250.28829956055,\"z\":29.26282119751},\"buy\":{\"y\":-1026.9453125,\"x\":250.28829956055,\"z\":29.26282119751}}', 0, 3, '{}', 0.1),
(5, 'Cool Beans', 'Blokkenpark 2', 'De verste koffiebonen uit Nieuwstad!', 'Cool Beans Winkel', 'steam:11000010e331a26', 10000, 30, '{\"actions\":{\"y\":-981.70611572266,\"x\":264.85800170898,\"z\":29.362478256226},\"buy\":{\"y\":-981.70611572266,\"x\":264.85800170898,\"z\":29.362478256226}}', 0, 3, '{}', 0.1),
(6, 'Pall Mall', 'Blokkenpark 4', 'De lekkerste rookwaren van Nieuwstad', 'PALL MALL', NULL, 20000, 60, '{\"actions\":{\"x\":278.59573364258,\"z\":29.210670471191,\"y\":-1028.560546875},\"buy\":{\"x\":278.59573364258,\"z\":29.210670471191,\"y\":-1028.560546875}}', 0, 6, '{}', 0.1),
(7, 'Elk Ridge Hotel', 'Blokkenpark 1A', '6 sterren hotel', 'Elk Ridge Hotel', NULL, 30000, 90, '{\"actions\":{\"y\":-937.32965087891,\"z\":29.391338348389,\"x\":285.54470825195},\"buy\":{\"y\":-937.32965087891,\"z\":29.391338348389,\"x\":285.54470825195}}', 0, 9, '{}', 0.1),
(8, 'Douwe Egberts Koffiewinkel', 'Blokkenpark 10', 'De lekkerste koffie uit Nieuwstad', 'Douwe Egberts', 'steam:11000010ef63187', 50000, 148, '{\"buy\":{\"z\":29.357330322266,\"y\":-1028.1353759766,\"x\":128.0284576416},\"actions\":{\"z\":29.357330322266,\"y\":-1028.1353759766,\"x\":128.0284576416}}', 498, 15, '{}', 0.05),
(9, 'Crucial Fix', 'Blokkenpark 12', 'Tosti\'s sinds 1983', 'Crucial Fix', NULL, 15000, 45, '{\"buy\":{\"z\":29.254652023315,\"y\":-834.43853759766,\"x\":274.04437255859},\"actions\":{\"z\":29.254652023315,\"y\":-834.43853759766,\"x\":274.04437255859}}', 0, 6, '{}', 0.1),
(10, 'Maison Ricard', 'Blokkenpark 14', 'Bed & Breakfast op de mooiste locatie', 'Maison Ricard', '', 25000, 72, '{\"buy\":{\"z\":31.164237976074,\"y\":-831.89050292969,\"x\":144.19119262695},\"actions\":{\"z\":31.164237976074,\"y\":-831.89050292969,\"x\":144.19119262695}}', 0, 8, '{}', 0.1),
(11, 'KnowWear', 'Hawick Avanue 100', 'De kleding die bij de past', 'KnowWear', NULL, 33000, 98, '{\"buy\":{\"x\":27.034729003906,\"y\":-168.36349487305,\"z\":55.59228515625},\"actions\":{\"x\":27.034729003906,\"y\":-168.36349487305,\"z\":55.59228515625}}', 0, 10, '{}', 0.09),
(12, 'Het Visnet', 'Hawick Avenue 102', 'Alles voor het vissen op 1 plek', 'Het Visnet', NULL, 7500, 20, '{\"buy\":{\"x\":15.075916290283,\"y\":-164.4216003418,\"z\":55.721817016602},\"actions\":{\"x\":15.075916290283,\"y\":-164.4216003418,\"z\":55.721817016602}}', 0, 3, '{}', 0.085),
(13, 'Retter de Knet', 'Hawick Avenue 104', 'Naar uw betere bed', 'Retter de Knet', NULL, 49650, 139, '{\"buy\":{\"x\":4.9441986083984,\"y\":-160.6886138916,\"z\":56.215766906738},\"actions\":{\"x\":4.9441986083984,\"y\":-160.6886138916,\"z\":56.215766906738}}', 0, 14, '{}', 0.15),
(14, 'Flikker Boekjes', 'Hawick Avenue 106', 'De leukste boekjes voor onderweg', 'Flikker Boekjes', NULL, 19950, 59, '{\"buy\":{\"x\":-1.7595168352127,\"y\":-157.03012084961,\"z\":56.396263122559},\"actions\":{\"x\":-1.7595168352127,\"y\":-157.03012084961,\"z\":56.396263122559}}', 0, 6, '{}', 0.09);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `businesses`
--
ALTER TABLE `businesses`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `businesses`
--
ALTER TABLE `businesses`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

```

**Comment by dutchplayers** [comment] 2019-12-21 23:57
The actual issue the player will have is; the bought business is not synced directly, but only after a client restart. If the player does not restart the game, they can buy the business over and over again.

**Comment by Elipse458** [comment] 2019-12-22 09:40
@dutchplayers 

> The actual issue the player will have is; the bought business is not synced directly

i'm pretty sure that's just caused by this error and isn't the actual issue, i just applied a fix and tested and it works fine now, i'll push changes and leave this issue open
if nothing happens after 3 days, i'll close this

**Comment by dutchplayers** [comment] 2019-12-23 13:12
Hello, thank you for responding!

I've updated the files, but i do still get thios error in my server log (actual issue): 
`[91mSCRIPT ERROR: @el_business/server.lua:20: attempt to index a nil value (field '?')[0m
[93m> callback[0m ([36m@el_business/server.lua[0m:99)
[93m> fn[0m ([36m@mysql-async/lib/MySQL.lua[0m:197)`

This is when i buy a business (can buy it over and over again (player issue)):
![20191223141048_1](https://user-images.githubusercontent.com/53178920/71359840-369c0600-258e-11ea-8a74-a38dcbb4ca6b.jpg)

**Comment by dutchplayers** [comment] 2019-12-23 13:15
(btw) our server is not open yet (opening early 2020), so i can try multiple solutions, even deleting my DB (no one will cry).

**Comment by Elipse458** [comment] 2019-12-23 15:45
@dutchplayers is your server hosted on windows?

**Comment by dutchplayers** [comment] 2019-12-23 15:46
yes

**Comment by Elipse458** [comment] 2019-12-23 15:46
aaaaaaaand we're home lol
i only have a linux server and it works fine there so if you're up for some testing, hmu on discord

**Comment by dutchplayers** [comment] 2019-12-23 15:48
Sure! :) Geoffrey#1998

**Comment by Elipse458** [comment] 2019-12-23 16:03
the issue seems to be with the businesses table, run this
```sql
UPDATE businesses SET owner=NULL WHERE owner IS NOT NULL AND NOT EXISTS (SELECT 1 FROM users WHERE businesses.owner = users.identifier)```
this query can be found in the readme file, this will set owner to NULL in where the owner doesn't exist in the users table anymore, i'll add a check or something for this

**Closed** 2019-12-23 16:03 UTC
Labels: good first issue, invalid
